-- Guess my number game
--
-- A Lua version of a silly game I made on my programmable
-- calculator when I was bored in math class in 1987, with a couple of
-- additions like input validation and computer guesses.
--
-- Copyright (c) 2026 Matthew Helmke for the Lua version (this one)
--    with assistance from Claude Code (claude.ai/code)
--    using the claude-opus-4-8 model; the initial port was generated by
--    the local gpt-oss-20b model in an agentic code-generation bake-off
--
-- To run:
--   lua guessnumber.lua
--
-- This program is free software; you can redistribute it and/or
-- modify it under the terms of the GNU General Public License
-- as published by the Free Software Foundation; either version 2
-- of the License, or (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

-- Print a description of the game, with rules, to the screen
io.write([[Welcome to Guess My Number!

The computer will select a random whole number between 1 and 100.
Your goal is to guess that number. You will get a turn, then a computer
player will get a turn. Each of you are aware of the other's guesses.
The first one to guess the number correctly will win. Try to guess in
as few turns as possible.

Here we go!


]])

-- Get a random number, or a fixed one from GMN_SECRET for parity testing
local secretnumber
local _gmn_secret = os.getenv("GMN_SECRET") or ""
if _gmn_secret:match("^%d+$") and tonumber(_gmn_secret) >= 1 and tonumber(_gmn_secret) <= 100 then
    secretnumber = tonumber(_gmn_secret)
else
    math.randomseed(os.time())
    secretnumber = math.random(1, 100)
end

-- set all our initial values
local userguess = 0
local totalguesses = 0
local lowmax = 1
local highmax = 100

-- the main bit
while true do
    -- let the user input any number they want
    io.write("What is your guess? ")
    local userguessunvalidated = io.read("*l") or ""
    -- remove leading and trailing spaces
    userguessunvalidated = userguessunvalidated:match("^%s*(.-)%s*$") or ""

    -- verify the guess is a number
    if not userguessunvalidated:match("^%d+$") then
        io.write([[Only whole numbers from 1 to 100 are allowed.
Please try again.

]])
        goto continue
    end
    -- make sure the guess is an integer in the right range
    userguess = tonumber(userguessunvalidated)
    if userguess <= 0 or userguess >= 101 then
        io.write([[Only whole numbers from 1 to 100 are allowed. Your guess is out of range.
Please try again.

]])
        goto continue
    end

    -- this is a real guess, so count it
    totalguesses = totalguesses + 1

    -- some taunts for silly errors in user guesses
    if userguess < lowmax then
        io.write([[That guess was lower than a previous guess that was too low. Pay attention!

]])
    end
    if userguess > highmax then
        io.write([[Wake up! That guess was higher than an earlier guess that was too high.

]])
    end

    -- evaluate the guess
    if userguess > secretnumber then
        io.write([[Your guess is too high.

]])
        if userguess <= highmax then
            highmax = userguess - 1
        end
    elseif userguess < secretnumber then
        io.write([[Your guess is too low.

]])
        if userguess >= lowmax then
            lowmax = userguess + 1
        end
    else
        io.write([[
*********************************************
   Your guess is correct! Congratulations!
   It took ]] .. totalguesses .. [[ total guesses.
*********************************************

]])
        break
    end

    -- the computer's guess uses a binary-search midpoint within current bounds
    local computerguess = math.floor((lowmax + highmax) / 2)
    totalguesses = totalguesses + 1
    if computerguess > secretnumber then
        io.write([[The computer guessed ]] .. computerguess .. [[ and that was too high.
Please try again.

]])
        highmax = computerguess - 1
    elseif computerguess < secretnumber then
        io.write([[The computer guessed ]] .. computerguess .. [[ and that was too low.
Please try again.

]])
        lowmax = computerguess + 1
    else
        io.write([[
**********************************************
   The computer's guess of ]] .. computerguess .. [[ is correct!
   It took ]] .. totalguesses .. [[ total guesses.
**********************************************

]])
        break
    end

    -- these taunts are just for my amusement and to keep the game from being too terribly long
    if totalguesses == 8 then
        io.write([[
This is a hard number, isn't it?

]])
    end
    if totalguesses == 12 then
        io.write([[
Wow! You are really bad at this.

]])
    end
    if totalguesses >= 16 then
        io.write([[
You're taking too long, I can't handle it any more.

G A M E   O V E R

]])
        break
    end

    ::continue::
end
